/**
 * Attendance module public API (Phase A facade).
 * Runtime implementation remains src/lib/hr/attendance/branchAttendance.service.ts
 */
import 'server-only';

export {
  AttendanceDomainError,
  AttendanceCommandError,
  resolveAdminPutAttendanceStatus,
  type AttendanceRow,
  ADMIN_BULK_SUCCESS_MESSAGE,
  WORK_ON_DAY_OFF_DEFAULT_REASON,
  WORK_ON_DAY_OFF_SOURCE_TAG,
  RESTORE_PRESENT_SOURCE,
  RESTORE_PRESENT_DAY_OFF_SOURCE,
  RESTORE_PRESENT_FAILURE_MESSAGE,
  type SaveAdminAttendanceInput,
  type SaveAdminAttendanceResult,
  type SaveAdminAttendanceBulkInput,
  type SaveAdminAttendanceBulkSummary,
  type SaveLegacyEmployeeAttendanceInput,
  type SaveLegacyEmployeeAttendanceResult,
  type UpdateLegacyEmployeeAttendanceByIdInput,
  type UpdateLegacyEmployeeAttendanceByIdResult,
  type WorkOnDayOffInput,
  type WorkOnDayOffResult,
  type RestorePresentInput,
  type RestorePresentResult,
  SCHEDULE_CONTROL_DAY_OFF_SOURCE,
  SCHEDULE_CONTROL_DAY_OFF_REVERT_SOURCE,
  type ApplyScheduleControlDayOffAttendanceInput,
  type RevertScheduleControlDayOffAttendanceInput,
  type RevertScheduleControlDayOffAttendanceResult,
  type MarkAutoAbsenceAttendanceInput,
  type AttendanceWriteDb,
  type PersistNightlyDefaultFillAttendanceInput,
  type RelocateClosedAttendanceFromBranchInput,
  type RelocateClosedAttendanceTowardDestinationInput,
  evaluateActiveOpenCreation,
  willResultInOpenSession,
  classifyOpenSession,
  type OpenAttendanceSession,
  type AttendanceSessionKind,
  ACTIVE_SESSION_ALREADY_OPEN_CODE,
  ACTIVE_SESSION_ALREADY_OPEN_MESSAGE,
} from './domain';

export {
  assertEmployeeEligibleForBranchAttendance,
  checkInEmployee,
  checkOutEmployee,
  getBranchAttendanceByEmpDate,
  getOpenAttendanceForEmployee,
  loadAttendanceOwnedByBranch,
  resolveAttendanceWorkDate,
  saveAdminAttendance,
  saveLegacyEmployeeAttendance,
  updateLegacyEmployeeAttendanceById,
  saveAdminAttendanceBulk,
  workOnDayOff,
  restorePresent,
  applyScheduleControlDayOffAttendance,
  revertScheduleControlDayOffAttendance,
  markAutoAbsenceAttendance,
  persistNightlyDefaultFillAttendance,
  relocateClosedAttendanceFromBranch,
  relocateClosedAttendanceTowardDestination,
  ensurePresentAttendancePlaceholder,
  listOpenSessionsForEmployee,
  listStaleOpenSessionsForEmployee,
  inventoryOpenAttendanceSessions,
  assertActiveOpenAllowed,
  AttendanceCommandService,
} from './application';
